# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- dev
pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  testsProjects: 'cowork.csproj'

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: "dotnet restore"
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '$(solution)'

    
- task: DotNetCoreCLI@2
  displayName: "dotnet Build"
  inputs:
    command: 'build'
    projects: '$(solution)'


- task: DotNetCoreCLI@2
  displayName: "dotnet test"
  inputs:
    command: 'test'
    projects: '$(testsProjects)'


- task: DotNetCoreCLI@2
  displayName: "dotnet publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true


- task: PublishBuildArtifacts@1
  displayName: "publish artifact"
  inputs:
  platform: '$(buildPlatform)'
  configuration: '$(buildConfiguration)'

