version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=cowork;username=coworkuser;password=coworkuser"
    networks:
      - dockerapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/db.sql :/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: "coworkuser"
      POSTGRES_PASSWORD: "coworkuser"
      POSTGRES_DB: "cowork"
    networks:
      - dockerapi-dev
volumes:
  db_volume: